version: 2
jobs:
  build:
    working_directory: ~/circleci-blog
    docker:
      - image: circleci/openjdk:13-buster
    steps:
      - checkout
      - restore_cache:
          key: circleci-blog-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-blog-{{ checksum "pom.xml" }}
      - run: mvn package
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target/blog-0.0.1-SNAPSHOT.jar
